name: codependence

on:
  workflow_run:
    workflows:
      - 'update codependencies'
  push:
    branches:
      - master
      - update-dependencies
  pull_request:
    branches:
      - master
      - update-dependencies

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm lint
        env:
          CI: true
